version: '3.8'

services:

  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik.toml:/etc/traefik/traefik.toml
      - acme.json:/acme.json
    labels:
      - "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://(www\\.)(.+)"
      - "traefik.http.middlewares.strip-www.redirectregex.replacement=https://$${2}"
      - "traefik.http.middlewares.strip-www.redirectregex.permanent=true"
    restart: always
    networks:
      - web


  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3004:3306"
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: C2SMR-wRjFqVJ6
      MYSQL_USER: C2SMR
      MYSQL_PASSWORD: C2SMR-wRjFqVJ6
      MYSQL_DATABASE: C2SMR
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
    container_name: api
    networks:
      - web
    environment:
      RASPBERRY_KEY: ${RASPBERRY_KEY}
      DB_NAME_MYSQL: ${DB_NAME_MYSQL}
      HOST_MYSQL: ${HOST_MYSQL}
      PASSWORD_MYSQL: ${PASSWORD_MYSQL}
      USER_MYSQL: ${USER_MYSQL}
    volumes:
      - ./api:/python-docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.c2smr.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"

  front:
    build:
      context: ./front
    container_name: front
    networks:
      - web
    volumes:
      - ./front:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`c2smr.fr`,`www.c2smr.fr`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.middlewares=strip-www"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - web
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.c2smr.fr`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"


networks:
  web:
    external: true
